### ISSUE TITLE
npm install failure due to sed error

### ISSUE THREAD

**Issue by YalaTest** [dlenroc/node-testrail-api#3]
Hello,

`npm install dlenroc/node-testrail-api --production --save` seems to be failing due to this error

```
npm ERR! prepareGitDep 1> 
npm ERR! prepareGitDep > testrail@1.0.0 prepare /home/ysong/.npm/_cacache/tmp/git-clone-6f9a257a
npm ERR! prepareGitDep > npm run build
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > testrail@1.0.0 build /home/ysong/.npm/_cacache/tmp/git-clone-6f9a257a
npm ERR! prepareGitDep > rollup -c && sed -i '' 's/export default TestRail;/export default TestRail; export = TestRail;/' ./dist/TestRail.d.ts
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep src/TestRail.ts → dist/TestRail.node.js, dist/TestRail.node.mjs, dist/TestRail.browser.mjs, dist/TestRail.umd.js...
npm ERR! prepareGitDep created dist/TestRail.node.js, dist/TestRail.node.mjs, dist/TestRail.browser.mjs, dist/TestRail.umd.js in 1.9s
npm ERR! prepareGitDep sed: can't read s/export default TestRail;/export default TestRail; export = TestRail;/: No such file or directory
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 2
npm ERR! prepareGitDep npm ERR! testrail@1.0.0 build: `rollup -c && sed -i '' 's/export default TestRail;/export default TestRail; export = TestRail;/' ./dist/TestRail.d.ts`
npm ERR! prepareGitDep npm ERR! Exit status 2
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the testrail@1.0.0 build script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /home/ysong/.npm/_logs/2020-09-18T17_54_27_750Z-debug.log
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 2
npm ERR! prepareGitDep npm ERR! testrail@1.0.0 prepare: `npm run build`
npm ERR! prepareGitDep npm ERR! Exit status 2
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the testrail@1.0.0 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /home/ysong/.npm/_logs/2020-09-18T17_54_27_769Z-debug.log
npm ERR! prepareGitDep 
npm ERR! premature close
```

I think the problem is with this line 
```
rollup -c && sed -i '' 's/export default TestRail;/export default TestRail; export = TestRail;/' ./dist/TestRail.d.ts
```

where it fields
```
npm ERR! prepareGitDep sed: can't read s/export default TestRail;/export default TestRail; export = TestRail;/: No such file or directory
```

**Comment by dlenroc** [comment]
Thank you for catching this, could you try again to see if the issue is fixed

**Comment by maximehyh** [comment]
Hi @dlenroc, the issue seems to remain as I am currently having the same issue. 

```
npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > testrail@1.0.0 prepare /home/streamroot/.npm/_cacache/tmp/git-clone-5ac318b7
npm ERR! prepareGitDep > npm run build
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > testrail@1.0.0 build /home/streamroot/.npm/_cacache/tmp/git-clone-5ac318b7
npm ERR! prepareGitDep > rollup -c && replace-in-file 'export default TestRail;' 'export default TestRail; export = TestRail;' dist/TestRail.d.ts
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep /home/streamroot/.npm/_cacache/tmp/git-clone-5ac318b7/node_modules/rollup/dist/shared/loadConfigFile.js:478
npm ERR! prepareGitDep         ? (await import(url.pathToFileURL(fileName).href)).default
npm ERR! prepareGitDep                  ^^^^^^
npm ERR! prepareGitDep
npm ERR! prepareGitDep SyntaxError: Unexpected token import
npm ERR! prepareGitDep     at createScript (vm.js:80:10)
npm ERR! prepareGitDep     at Object.runInThisContext (vm.js:139:10)
npm ERR! prepareGitDep     at Module._compile (module.js:617:28)
npm ERR! prepareGitDep     at Object.Module._extensions..js (module.js:664:10)
npm ERR! prepareGitDep     at Module.load (module.js:566:32)
npm ERR! prepareGitDep     at tryModuleLoad (module.js:506:12)
npm ERR! prepareGitDep     at Function.Module._load (module.js:498:3)
npm ERR! prepareGitDep     at Module.require (module.js:597:17)
npm ERR! prepareGitDep     at require (internal/module.js:11:18)
npm ERR! prepareGitDep     at Object.<anonymous> (/home/streamroot/.npm/_cacache/tmp/git-clone-5ac318b7/node_modules/rollup/dist/bin/rollup:22:25)
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! testrail@1.0.0 build: `rollup -c && replace-in-file 'export default TestRail;' 'export default TestRail; export = TestRail;' dist/TestRail.d.ts`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the testrail@1.0.0 build script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /home/streamroot/.npm/_logs/2020-10-07T08_06_34_472Z-debug.log
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! testrail@1.0.0 prepare: `npm run build`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the testrail@1.0.0 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /home/streamroot/.npm/_logs/2020-10-07T08_06_34_600Z-debug.log
npm ERR! prepareGitDep
```

**Comment by dlenroc** [comment]
@maximehyh can you tell me which `node` and `npm` version are you using?
> based on the logs seems that unsupported NodeJS version is used
> [package.json#L35](https://github.com/dlenroc/node-testrail-api/blob/master/package.json#L35): NodeJS >=10 should be supported

**Comment by maximehyh** [comment]
@dlenroc oh right this error did came from a build done with a release of NodeJS <=10, sorry about that. 
The real thing is I am currently trying to troubleshoot an issue I have when building node-testrail-api in a Docker container with `node:13`. I can build without any issues but suddenly when I now run the container my service cannot find the module 

```
[2020-10-08T21:10:30.714Z] Error: Cannot find module 'testrail'
Require stack:
- /app/tester/src/test-suite/reporter/testRail-reporter.js
- /app/tester/src/testListener.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)
    at Function.Module._load (internal/modules/cjs/loader.js:838:27)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/tester/src/test-suite/reporter/testRail-reporter.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Module.m._compile (/app/tester/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Object.require.extensions.<computed> [as .js] (/app/tester/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:982:32)
```

I'll investigate a little more. 

Thanks

**Comment by dlenroc** [comment]
@maximehyh you made sure the dependencies show up in your `package.json` and `npm install` was used in build flow  ?
> this error usually occurs when the dependency is not installed or present in package.json

**Comment by maximehyh** [comment]
@dlenroc  Yes it is as `"testrail": "github:dlenroc/node-testrail-api"`
Well it looks like when I build with docker my `node_modules/testrail` is missing the `/dist` folder...
I do not get why it disappeared all of a sudden, could it be related to the recent changes you made on the lib?

**Comment by dlenroc** [comment]
no (if actual `npm` version is used) if you want you can create a repository with the setting you are using and maybe I can help you
> In any case, I plan to publish an already compiled version today on npmjs.com - this will solve all possible problems with installing directly from Github (+ will also allow using other package managers)

**Comment by maximehyh** [comment]
I ended re building on top of a previous commit and now everything is back to normal. I really do not get what happened but anyway. 
A npm package would be awesome. Thanks for the great work!

**Comment by dlenroc** [comment]
## NPM Package

#### Simple installation
```bash
npm install @dlenroc/testrail
```

#### Installation using import alias (requires NPM >=6.9.0)
> which make possible to use `require('testrail')` instead of `require('@dlenroc/testrail')`
```bash
npm install testrail@npm:@dlenroc/testrail
```

------
Reopen if still have issue with installation
